# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        java-version: [ '11', '14' ]

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Check the code format
        run: |
          mvn spotless:check
      - name: Start deepl-mock server
        run: |
          git clone git@github.com:DeepLcom/deepl-mock.git
          cd deepl-mock/
          sed -i '' 's/RUN npm audit//' Dockerfile
          docker image build -t deepl/deepl-mock .
          docker run -d --rm --name deepl-mock -p3000:3000 -p3001:3001 deepl/deepl-mock
      - name: Compile the main/test code
        run: |
          mvn test-compile --no-transfer-progress -DfailIfNoTests=false '-Dtest=tests.**.*Test' test
      - name: Stop deepl-mock server
        run: |
          docker stop deepl/deepl-mock
