# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      matrix:
        java-version: [ '11', '14' ]

    steps:
      - uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Check the code format
        run: |
          mvn spotless:check
      - name: Compile the main/test code
        run: |
          mvn test-compile --no-transfer-progress -DfailIfNoTests=false '-Dtest=tests.**.*Test' test
